// swift-tools-version: 5.6
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "YLCategory-Swift-MacOS",
    defaultLocalization: "en",
    platforms: [.macOS(.v10_14)],
    products: [
        // Products define the executables and libraries a package produces, making them visible to other packages.
        .library(
            name: "YLCategory-Swift-MacOS",
            targets: ["YLCategory-Swift-MacOS"]
        ),
    ],
    dependencies: [.package(url: "https://github.com/sparkle-project/Sparkle.git", from: "2.8.0")],
    targets: [
        // Targets are the basic building blocks of a package, defining a module or a test suite.
        // Targets can depend on other targets in this package and products from dependencies.
        .target(
            name: "YLCategory-Swift-MacOS",
            dependencies: [
                "Async",
                "NSAlert",
                "NSButton",
                "NSColor",
                "NSControl",
                "NSDate",
                "NSImage",
                "NSImageView",
                "NSObject",
                "NSOpenPanel",
                "NSResponder",
                "NSSavePanel",
                "NSScreen",
                "NSString",
                "NSTextField",
                "NSURL",
                "NSView",
                "NSWindow",
                "YLAppleReview",
                "YLAppleScript",
                "YLAppRating",
                "YLCFNotificationManager",
                "YLCollectionView",
                "YLControl",
                "YLFileAccess",
                "YLFlipView",
                "YLHud",
                "YLKit",
                "YLLanguage",
                "YLPermissionManager",
                "YLScrollLabel",
                "YLShortcutView",
                "YLSystemBeep",
                "YLTextField",
                "YLTheme",
                "YLTipButton",
                "YLUpdateManager",
                "YLUserDefaults",
                "YLWindowButton",
            ]
        ),
        .target(name: "Async"),
        .target(name: "NSAlert"),
        .target(name: "NSButton", dependencies: ["NSControl"]),
        .target(name: "NSColor"),
        .target(name: "NSControl"),
        .target(name: "NSDate"),
        .target(name: "NSImage"),
        .target(name: "NSImageView"),
        .target(name: "NSObject"),
        .target(name: "NSOpenPanel"),
        .target(name: "NSResponder"),
        .target(name: "NSSavePanel"),
        .target(name: "NSScreen"),
        .target(name: "NSString"),
        .target(name: "NSTextField"),
        .target(name: "NSURL"),
        .target(name: "NSView"),
        .target(name: "NSWindow"),
        .target(name: "YLAppleReview"),
        .target(name: "YLAppleScript", dependencies: ["YLHud"], resources: [.process("Resources")]),
        .target(name: "YLAppRating"),
        .target(name: "YLCFNotificationManager"),
        .target(name: "YLCollectionView"),
        .target(name: "YLControl"),
        .target(name: "YLFileAccess", resources: [.process("Resources")]),
        .target(name: "YLFlipView"),
        .target(name: "YLHud", resources: [.process("Resources")]),
        .target(name: "YLKit"),
        .target(name: "YLLanguage", resources: [.process("Resources")]),
        .target(name: "YLPermissionManager", resources: [.process("Resources")]),
        .target(name: "YLScrollLabel"),
        .target(name: "YLShortcutView", dependencies: ["YLHud"], resources: [.process("Resources")]),
        .target(name: "YLSystemBeep"),
        .target(name: "YLTextField"),
        .target(name: "YLTheme", resources: [.process("Resources")]),
        .target(name: "YLTipButton"),
        .target(name: "YLUpdateManager", dependencies: [.product(name: "Sparkle", package: "Sparkle")], resources: [.process("Resources")]),
        .target(name: "YLUserDefaults"),
        .target(name: "YLWindowButton"),
        .testTarget(
            name: "YLCategory-Swift-MacOSTests",
            dependencies: ["YLCategory-Swift-MacOS"]
        ),
    ]
)
